name: Code Check

on: [push, pull_request]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
    - name: Загрузка репозитория
      uses: actions/checkout@v3

    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установка flake8 и black
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Проверка синтаксиса
      run: |
        python -m compileall .

    - name: Автоформатирование с black
      run: |
        black . --exclude 'memes\.db' 
    
    # Код выше форматирует, 
    # Если потом захотим заменить на просто проверку:
    # black . --check --exclude 'memes\.db'

    - name: Проверка стиля с flake8
      run: |
        flake8 . --exclude=memes.db,__pycache__,.venv

    # - name: Запуск тестов #когда добавим тесты, они должны или храниться в ./tests или начинаться с test_*.py
    #   run: |
    #     pip install pytest
    #     pytest
